Metrics/MethodLength:
    Enabled: false
Metrics/AbcSize:
    Enabled: false
Style/Documentation:
    Enabled: false
Metrics/CyclomaticComplexity:
    Enabled: false
Metrics/PerceivedComplexity:
    Enabled: false
